# fly.toml app configuration file generated for work-tracking-backend on 2024-07-12T14:07:44+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'work-tracking-backend'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
